server:
  env: "${SERVER_ENV}"
  grpc:
    name: "${SERVICE_NAME}"
    ListenOn: 0.0.0.0:8001
    middlewares:
      stat: false
      prometheus: false
      shedding: false
      breaker: false
    telemetry:
      name: "inapp-${SERVICE_NAME}"
      endpoint: "${TELEMETRY_ENDPOINT}"
      batcher: otlpgrpc
  http:
    name: "${SERVICE_NAME}"
    host: 0.0.0.0
    port: ${SERVER_PORT}
    timeout: 30000
    middlewares:
      prometheus: false
      metrics: false
      shedding: false
    telemetry:
      name: "inapp-${SERVICE_NAME}"
      endpoint: "${TELEMETRY_ENDPOINT}"
      batcher: otlpgrpc

database:
  driver: "${DB_DRIVER}"
  host: "${DB_HOST}"
  port: ${DB_PORT}
  username: "${DB_USERNAME}"
  password: "${DB_PASSWORD}"
  name: "${DB_NAME}"
  schema-name: "${DB_SCHEMA_NAME}"

cache:
  stack: redis
  redis:
    host: "${REDIS_HOST}"
    pass: "${REDIS_PASSWORD}"
    db: ${REDIS_DB}

oauth:
  debug: ${OAUTH_DEBUG}
  hash-secret: "${OAUTH_HASH_SECRET}"
  private-key: "${OAUTH_PRIVATE_KEY}"
  public-key: "${OAUTH_PUBLIC_KEY}"
