// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.1
// 	protoc        v5.26.1
// source: api/authentication/authentication.proto

package authentication

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type TokenAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Issuer string `protobuf:"bytes,1,opt,name=issuer,proto3" json:"issuer,omitempty"`
}

func (x *TokenAuthReq) Reset() {
	*x = TokenAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuthReq) ProtoMessage() {}

func (x *TokenAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuthReq.ProtoReflect.Descriptor instead.
func (*TokenAuthReq) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{0}
}

func (x *TokenAuthReq) GetIssuer() string {
	if x != nil {
		return x.Issuer
	}
	return ""
}

type TokenAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	User   *UserData   `protobuf:"bytes,1,opt,name=user,proto3" json:"user,omitempty"`
	Client *ClientData `protobuf:"bytes,2,opt,name=client,proto3" json:"client,omitempty"`
}

func (x *TokenAuthResp) Reset() {
	*x = TokenAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *TokenAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TokenAuthResp) ProtoMessage() {}

func (x *TokenAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TokenAuthResp.ProtoReflect.Descriptor instead.
func (*TokenAuthResp) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{1}
}

func (x *TokenAuthResp) GetUser() *UserData {
	if x != nil {
		return x.User
	}
	return nil
}

func (x *TokenAuthResp) GetClient() *ClientData {
	if x != nil {
		return x.Client
	}
	return nil
}

type UserData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id         int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Email      string   `protobuf:"bytes,2,opt,name=email,proto3" json:"email,omitempty"`
	EmployeeId string   `protobuf:"bytes,3,opt,name=employee_id,proto3" json:"employee_id,omitempty"`
	Name       string   `protobuf:"bytes,4,opt,name=name,proto3" json:"name,omitempty"`
	Avatar     string   `protobuf:"bytes,5,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Department string   `protobuf:"bytes,6,opt,name=department,proto3" json:"department,omitempty"`
	Rank       string   `protobuf:"bytes,7,opt,name=rank,proto3" json:"rank,omitempty"`
	Position   string   `protobuf:"bytes,8,opt,name=position,proto3" json:"position,omitempty"`
	WorkPlace  string   `protobuf:"bytes,9,opt,name=work_place,proto3" json:"work_place,omitempty"`
	Phone      string   `protobuf:"bytes,10,opt,name=phone,proto3" json:"phone,omitempty"`
	Gender     int32    `protobuf:"varint,11,opt,name=gender,proto3" json:"gender,omitempty"`
	Roles      []string `protobuf:"bytes,12,rep,name=roles,proto3" json:"roles,omitempty"`
}

func (x *UserData) Reset() {
	*x = UserData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserData) ProtoMessage() {}

func (x *UserData) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserData.ProtoReflect.Descriptor instead.
func (*UserData) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{2}
}

func (x *UserData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UserData) GetEmail() string {
	if x != nil {
		return x.Email
	}
	return ""
}

func (x *UserData) GetEmployeeId() string {
	if x != nil {
		return x.EmployeeId
	}
	return ""
}

func (x *UserData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *UserData) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UserData) GetDepartment() string {
	if x != nil {
		return x.Department
	}
	return ""
}

func (x *UserData) GetRank() string {
	if x != nil {
		return x.Rank
	}
	return ""
}

func (x *UserData) GetPosition() string {
	if x != nil {
		return x.Position
	}
	return ""
}

func (x *UserData) GetWorkPlace() string {
	if x != nil {
		return x.WorkPlace
	}
	return ""
}

func (x *UserData) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *UserData) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UserData) GetRoles() []string {
	if x != nil {
		return x.Roles
	}
	return nil
}

type ClientData struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int32    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Uid    string   `protobuf:"bytes,2,opt,name=uid,proto3" json:"uid,omitempty"`
	Name   string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Scopes []string `protobuf:"bytes,4,rep,name=scopes,proto3" json:"scopes,omitempty"`
}

func (x *ClientData) Reset() {
	*x = ClientData{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientData) ProtoMessage() {}

func (x *ClientData) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientData.ProtoReflect.Descriptor instead.
func (*ClientData) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{3}
}

func (x *ClientData) GetId() int32 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ClientData) GetUid() string {
	if x != nil {
		return x.Uid
	}
	return ""
}

func (x *ClientData) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ClientData) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ClientAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	GrantType    string `protobuf:"bytes,1,opt,name=grant_type,proto3" json:"grant_type,omitempty"`
	ClientId     string `protobuf:"bytes,2,opt,name=client_id,proto3" json:"client_id,omitempty"`
	ClientSecret string `protobuf:"bytes,3,opt,name=client_secret,proto3" json:"client_secret,omitempty"`
}

func (x *ClientAuthReq) Reset() {
	*x = ClientAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthReq) ProtoMessage() {}

func (x *ClientAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthReq.ProtoReflect.Descriptor instead.
func (*ClientAuthReq) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{4}
}

func (x *ClientAuthReq) GetGrantType() string {
	if x != nil {
		return x.GrantType
	}
	return ""
}

func (x *ClientAuthReq) GetClientId() string {
	if x != nil {
		return x.ClientId
	}
	return ""
}

func (x *ClientAuthReq) GetClientSecret() string {
	if x != nil {
		return x.ClientSecret
	}
	return ""
}

type ClientAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *ClientAuthResp) Reset() {
	*x = ClientAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ClientAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClientAuthResp) ProtoMessage() {}

func (x *ClientAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClientAuthResp.ProtoReflect.Descriptor instead.
func (*ClientAuthResp) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{5}
}

type EcomAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *EcomAuthResp) Reset() {
	*x = EcomAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *EcomAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EcomAuthResp) ProtoMessage() {}

func (x *EcomAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EcomAuthResp.ProtoReflect.Descriptor instead.
func (*EcomAuthResp) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{6}
}

type UserAuthReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserAuthReq) Reset() {
	*x = UserAuthReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuthReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthReq) ProtoMessage() {}

func (x *UserAuthReq) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthReq.ProtoReflect.Descriptor instead.
func (*UserAuthReq) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{7}
}

type UserAuthResp struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *UserAuthResp) Reset() {
	*x = UserAuthResp{}
	if protoimpl.UnsafeEnabled {
		mi := &file_api_authentication_authentication_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *UserAuthResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserAuthResp) ProtoMessage() {}

func (x *UserAuthResp) ProtoReflect() protoreflect.Message {
	mi := &file_api_authentication_authentication_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserAuthResp.ProtoReflect.Descriptor instead.
func (*UserAuthResp) Descriptor() ([]byte, []int) {
	return file_api_authentication_authentication_proto_rawDescGZIP(), []int{8}
}

var File_api_authentication_authentication_proto protoreflect.FileDescriptor

var file_api_authentication_authentication_proto_rawDesc = []byte{
	0x0a, 0x27, 0x61, 0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74,
	0x69, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x20, 0x70, 0x6d, 0x63, 0x2e, 0x69,
	0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75,
	0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x22, 0x26, 0x0a, 0x0c, 0x54,
	0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x16, 0x0a, 0x06, 0x69,
	0x73, 0x73, 0x75, 0x65, 0x72, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x73, 0x73,
	0x75, 0x65, 0x72, 0x22, 0x95, 0x01, 0x0a, 0x0d, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74,
	0x68, 0x52, 0x65, 0x73, 0x70, 0x12, 0x3e, 0x0a, 0x04, 0x75, 0x73, 0x65, 0x72, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x2a, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e,
	0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69,
	0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x52,
	0x04, 0x75, 0x73, 0x65, 0x72, 0x12, 0x44, 0x0a, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x18,
	0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x2c, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70,
	0x70, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f,
	0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44,
	0x61, 0x74, 0x61, 0x52, 0x06, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x22, 0xb2, 0x02, 0x0a, 0x08,
	0x55, 0x73, 0x65, 0x72, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x14, 0x0a, 0x05, 0x65, 0x6d, 0x61, 0x69,
	0x6c, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x65, 0x6d, 0x61, 0x69, 0x6c, 0x12, 0x20,
	0x0a, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x0b, 0x65, 0x6d, 0x70, 0x6c, 0x6f, 0x79, 0x65, 0x65, 0x5f, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x61, 0x76, 0x61, 0x74, 0x61, 0x72, 0x12, 0x1e, 0x0a, 0x0a,
	0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x64, 0x65, 0x70, 0x61, 0x72, 0x74, 0x6d, 0x65, 0x6e, 0x74, 0x12, 0x12, 0x0a, 0x04,
	0x72, 0x61, 0x6e, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x72, 0x61, 0x6e, 0x6b,
	0x12, 0x1a, 0x0a, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x08, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x70, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1e, 0x0a, 0x0a,
	0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x77, 0x6f, 0x72, 0x6b, 0x5f, 0x70, 0x6c, 0x61, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05,
	0x70, 0x68, 0x6f, 0x6e, 0x65, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52, 0x05, 0x70, 0x68, 0x6f,
	0x6e, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x18, 0x0b, 0x20, 0x01,
	0x28, 0x05, 0x52, 0x06, 0x67, 0x65, 0x6e, 0x64, 0x65, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x72, 0x6f,
	0x6c, 0x65, 0x73, 0x18, 0x0c, 0x20, 0x03, 0x28, 0x09, 0x52, 0x05, 0x72, 0x6f, 0x6c, 0x65, 0x73,
	0x22, 0x5a, 0x0a, 0x0a, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x44, 0x61, 0x74, 0x61, 0x12, 0x0e,
	0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x02, 0x69, 0x64, 0x12, 0x10,
	0x0a, 0x03, 0x75, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x03, 0x75, 0x69, 0x64,
	0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x09, 0x52, 0x06, 0x73, 0x63, 0x6f, 0x70, 0x65, 0x73, 0x22, 0x73, 0x0a, 0x0d,
	0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x12, 0x1e, 0x0a,
	0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0a, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x12, 0x1c, 0x0a,
	0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x09, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x12, 0x24, 0x0a, 0x0d, 0x63,
	0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65, 0x74, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x63, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x5f, 0x73, 0x65, 0x63, 0x72, 0x65,
	0x74, 0x22, 0x10, 0x0a, 0x0e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0e, 0x0a, 0x0c, 0x45, 0x63, 0x6f, 0x6d, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x73, 0x70, 0x22, 0x0d, 0x0a, 0x0b, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x22, 0x0e, 0x0a, 0x0c, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x32, 0xc9, 0x03, 0x0a, 0x0e, 0x41, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x6b, 0x0a, 0x08, 0x56, 0x61, 0x6c, 0x69, 0x64, 0x61, 0x74,
	0x65, 0x12, 0x2e, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x71, 0x1a, 0x2f, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x70, 0x0a, 0x0b, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x2f, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x30, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68,
	0x52, 0x65, 0x73, 0x70, 0x12, 0x6c, 0x0a, 0x09, 0x45, 0x63, 0x6f, 0x6d, 0x54, 0x6f, 0x6b, 0x65,
	0x6e, 0x12, 0x2f, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64,
	0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61,
	0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x43, 0x6c, 0x69, 0x65, 0x6e, 0x74, 0x41, 0x75, 0x74, 0x68, 0x52,
	0x65, 0x71, 0x1a, 0x2e, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69,
	0x64, 0x65, 0x6e, 0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a,
	0x61, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x45, 0x63, 0x6f, 0x6d, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65,
	0x73, 0x70, 0x12, 0x6a, 0x0a, 0x09, 0x55, 0x73, 0x65, 0x72, 0x54, 0x6f, 0x6b, 0x65, 0x6e, 0x12,
	0x2d, 0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64, 0x65, 0x6e,
	0x74, 0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x71, 0x1a, 0x2e,
	0x2e, 0x70, 0x6d, 0x63, 0x2e, 0x69, 0x6e, 0x61, 0x70, 0x70, 0x2e, 0x69, 0x64, 0x65, 0x6e, 0x74,
	0x69, 0x74, 0x79, 0x2e, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x69, 0x7a, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x41, 0x75, 0x74, 0x68, 0x52, 0x65, 0x73, 0x70, 0x42, 0x31,
	0x5a, 0x2f, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62, 0x2f, 0x74, 0x72, 0x6f, 0x6e, 0x67, 0x6c, 0x76,
	0x5f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x5f, 0x61, 0x75, 0x74, 0x68, 0x6f, 0x72, 0x2f, 0x61,
	0x70, 0x69, 0x2f, 0x61, 0x75, 0x74, 0x68, 0x65, 0x6e, 0x74, 0x69, 0x63, 0x61, 0x74, 0x69, 0x6f,
	0x6e, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_api_authentication_authentication_proto_rawDescOnce sync.Once
	file_api_authentication_authentication_proto_rawDescData = file_api_authentication_authentication_proto_rawDesc
)

func file_api_authentication_authentication_proto_rawDescGZIP() []byte {
	file_api_authentication_authentication_proto_rawDescOnce.Do(func() {
		file_api_authentication_authentication_proto_rawDescData = protoimpl.X.CompressGZIP(file_api_authentication_authentication_proto_rawDescData)
	})
	return file_api_authentication_authentication_proto_rawDescData
}

var file_api_authentication_authentication_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_api_authentication_authentication_proto_goTypes = []interface{}{
	(*TokenAuthReq)(nil),   // 0: pmc.inapp.identity.authorization.TokenAuthReq
	(*TokenAuthResp)(nil),  // 1: pmc.inapp.identity.authorization.TokenAuthResp
	(*UserData)(nil),       // 2: pmc.inapp.identity.authorization.UserData
	(*ClientData)(nil),     // 3: pmc.inapp.identity.authorization.ClientData
	(*ClientAuthReq)(nil),  // 4: pmc.inapp.identity.authorization.ClientAuthReq
	(*ClientAuthResp)(nil), // 5: pmc.inapp.identity.authorization.ClientAuthResp
	(*EcomAuthResp)(nil),   // 6: pmc.inapp.identity.authorization.EcomAuthResp
	(*UserAuthReq)(nil),    // 7: pmc.inapp.identity.authorization.UserAuthReq
	(*UserAuthResp)(nil),   // 8: pmc.inapp.identity.authorization.UserAuthResp
}
var file_api_authentication_authentication_proto_depIdxs = []int32{
	2, // 0: pmc.inapp.identity.authorization.TokenAuthResp.user:type_name -> pmc.inapp.identity.authorization.UserData
	3, // 1: pmc.inapp.identity.authorization.TokenAuthResp.client:type_name -> pmc.inapp.identity.authorization.ClientData
	0, // 2: pmc.inapp.identity.authorization.Authentication.Validate:input_type -> pmc.inapp.identity.authorization.TokenAuthReq
	4, // 3: pmc.inapp.identity.authorization.Authentication.ClientToken:input_type -> pmc.inapp.identity.authorization.ClientAuthReq
	4, // 4: pmc.inapp.identity.authorization.Authentication.EcomToken:input_type -> pmc.inapp.identity.authorization.ClientAuthReq
	7, // 5: pmc.inapp.identity.authorization.Authentication.UserToken:input_type -> pmc.inapp.identity.authorization.UserAuthReq
	1, // 6: pmc.inapp.identity.authorization.Authentication.Validate:output_type -> pmc.inapp.identity.authorization.TokenAuthResp
	5, // 7: pmc.inapp.identity.authorization.Authentication.ClientToken:output_type -> pmc.inapp.identity.authorization.ClientAuthResp
	6, // 8: pmc.inapp.identity.authorization.Authentication.EcomToken:output_type -> pmc.inapp.identity.authorization.EcomAuthResp
	8, // 9: pmc.inapp.identity.authorization.Authentication.UserToken:output_type -> pmc.inapp.identity.authorization.UserAuthResp
	6, // [6:10] is the sub-list for method output_type
	2, // [2:6] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_api_authentication_authentication_proto_init() }
func file_api_authentication_authentication_proto_init() {
	if File_api_authentication_authentication_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_api_authentication_authentication_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*TokenAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientData); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*ClientAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*EcomAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuthReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_api_authentication_authentication_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*UserAuthResp); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_api_authentication_authentication_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_authentication_authentication_proto_goTypes,
		DependencyIndexes: file_api_authentication_authentication_proto_depIdxs,
		MessageInfos:      file_api_authentication_authentication_proto_msgTypes,
	}.Build()
	File_api_authentication_authentication_proto = out.File
	file_api_authentication_authentication_proto_rawDesc = nil
	file_api_authentication_authentication_proto_goTypes = nil
	file_api_authentication_authentication_proto_depIdxs = nil
}
